quarkus.http.port=8080

# Use random port in test mode to avoid conflicts with dev mode
%test.quarkus.http.port=0

# Database - H2 embedded for dev/test
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:ocpp;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.log.sql=false

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/changelog-master.yaml
%test.quarkus.log.category."io.quarkus.config".level=ERROR

quarkus.websockets-next.server.supported-subprotocols=ocpp1.6
